### ISSUE TITLE
Request for Project Update and Renewed Activity

### ISSUE THREAD

**Issue by ywnkm** [kotpot/cosmos-protocol#1]
I would like to express my sincere appreciation for your contributions to the open-source community. Your [cosmos-protocol](https://github.com/kotpot/cosmos-protocol) has been a valuable resource for many of us, and it has played a pivotal role in our life.

I understand that maintaining an open-source project can be demanding and time-consuming, and I respect the effort you have already put into it. However, I've noticed that the project has not seen updates for quite some time. As an enthusiastic user and contributor, I'm genuinely concerned about its stagnation. I believe in the importance of keeping open-source projects up to date and active to benefit the wider community.

The reason I'm reaching out today is to kindly request if there is any possibility for you to consider reviving this project. It would be wonderful to see it thrive once again, given its potential and the user base it has garnered over time. If you are facing challenges, whether they are time constraints, resource limitations, or any other issues, I'm sure the community would be willing to help and support you in any way possible.

I genuinely hope that we can see [cosmos-protocol](https://github.com/kotpot/cosmos-protocol) thrive once more, and I'm eager to assist in any way I can. Please consider this request, and let's work together to bring this fantastic project back to life.

**Comment by ywnkm** [comment]
@IkuzItsuki

**Comment by korilin** [comment]
> I would like to express my sincere appreciation for your contributions to the open-source community. Your [cosmos-protocol](https://github.com/kotpot/cosmos-protocol) has been a valuable resource for many of us, and it has played a pivotal role in our life.
> 
> I understand that maintaining an open-source project can be demanding and time-consuming, and I respect the effort you have already put into it. However, I've noticed that the project has not seen updates for quite some time. As an enthusiastic user and contributor, I'm genuinely concerned about its stagnation. I believe in the importance of keeping open-source projects up to date and active to benefit the wider community.
> 
> The reason I'm reaching out today is to kindly request if there is any possibility for you to consider reviving this project. It would be wonderful to see it thrive once again, given its potential and the user base it has garnered over time. If you are facing challenges, whether they are time constraints, resource limitations, or any other issues, I'm sure the community would be willing to help and support you in any way possible.
> 
> I genuinely hope that we can see [cosmos-protocol](https://github.com/kotpot/cosmos-protocol) thrive once more, and I'm eager to assist in any way I can. Please consider this request, and let's work together to bring this fantastic project back to life.

Hi @ywnkm ,thanks for your recognition of Cosmos.

The project wasn't be suspended. The [cosmos-client](https://github.com/kotpot/cosmos-client) is still being carried out by @IkuzItsuki. I have been too busy lately, and there are still many design details that haven't been determined, that's why there's no update here.

The cosmos-protocol is only used to store shared data classes, and any suggestions for cosmos can be feedback into the issue or discussion in [cosmos](https://github.com/kotpot/cosmos), which will be the conclusion of Cosmos.
